# Generated by Django 4.2.11 on 2026-06-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_table_is_accepting_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorderitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableorderitem',
            name='cancelled_by_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('BILLED', 'Billed')], default='OPEN', max_length=10),
        ),
        migrations.CreateModel(
            name='KitchenNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tables.tablesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
