# Generated by Django 4.2.11 on 2026-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_batch_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorderbatch',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tableorderbatch',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
