# Generated by Django 4.2.11 on 2026-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_invoice_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Number of packages purchased', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per package', max_digits=10),
        ),
    ]
