# Generated by Django 4.2.11 on 2026-07-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_fooditem_is_combo_comboccomponent'),
        ('inventory', '0003_alter_invoiceitem_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('current_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.ingredient'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='packaging_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.packagingitem'),
        ),
        migrations.CreateModel(
            name='FoodTypePackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('PARCEL', 'Parcel')], max_length=10)),
                ('qty_per_serving', models.PositiveIntegerField(default=1)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_mappings', to='menu.foodtype')),
                ('packaging_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type_mappings', to='inventory.packagingitem')),
            ],
            options={
                'ordering': ['food_type__name', 'order_type'],
                'unique_together': {('food_type', 'packaging_item', 'order_type')},
            },
        ),
    ]
