# Generated by Django 4.2.11 on 2026-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BILL', 'Payment Bill'), ('ABSENT_STAFF', 'Absent – Staff'), ('ABSENT_ADMIN', 'Absent – Admin'), ('LOW_STOCK', 'Low Stock Alert')], max_length=20)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='e.g. order:123 or attendance:456', max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
