# Generated by Django 4.2.11 on 2026-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Restaurant', max_length=200)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='GST percentage applied to all bills', max_digits=5)),
                ('admin_whatsapp', models.CharField(blank=True, help_text='Admin WhatsApp number with country code (e.g. 919876543210)', max_length=20)),
                ('wa_api_token', models.CharField(blank=True, help_text='Meta WhatsApp Cloud API bearer token', max_length=500, verbose_name='WhatsApp API Token')),
                ('wa_phone_id', models.CharField(blank=True, help_text='Phone Number ID from Meta Business Suite', max_length=100, verbose_name='WhatsApp Phone Number ID')),
                ('wa_billing_enabled', models.BooleanField(default=False, help_text='Send itemised bill to customer on WhatsApp after payment', verbose_name='Send bill after payment')),
                ('wa_absent_staff_enabled', models.BooleanField(default=False, help_text='Send absent notification to staff member on WhatsApp', verbose_name='Notify absent staff')),
                ('wa_absent_admin_enabled', models.BooleanField(default=False, help_text='Send absent alert to admin WhatsApp', verbose_name='Notify admin on absent')),
                ('wa_low_stock_enabled', models.BooleanField(default=False, help_text='Send low-stock alerts to admin WhatsApp', verbose_name='Low stock alert to admin')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
            },
        ),
    ]
