# Generated by Django 4.2.11 on 2026-06-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='kitchen_cancel_pin',
            field=models.CharField(blank=True, default='', help_text='PIN kitchen staff must enter to cancel or reduce order items (leave blank to disable PIN check)', max_length=20),
        ),
    ]
