# Generated by Django 4.2.11 on 2026-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_order_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('PARCEL', 'Parcel')], default='DINE_IN', max_length=10),
        ),
    ]
