# Generated by Django 4.2.11 on 2026-07-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kitchen_role_linked_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('BILLER', 'Biller'), ('KITCHEN', 'Kitchen')], default='BILLER', max_length=10),
        ),
    ]
