# Generated by Django 4.2.11 on 2026-07-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_kitchen_tableorderitem_status'),
        ('accounts', '0003_add_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tables.kitchen'),
        ),
    ]
